openapi: 3.0.0
info:
  description: Simple inventory of keyboards ordered
  version: "1.0.0"
  title: Keyboard Order Inventory
  contact:
    email: aiden@lonquist.net
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Keyboards
    description: Operations available to keyboard orders
paths:
  /stats:
    get:
      tags:
        - Keyboards
      summary: Gets the event stats
      operationId: app.get_stats
      description: gets the stats of both the standard and custom orders
      responses:
        '200':
          description: Successfully returned a list of order enents
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    ReadingStats:
      required:
      - num_standard_orders
      - max_standard_order_id
      - num_custom_orders
      - max_custom_order_id
      properties:
        num_standard_orders:
          type: integer
          example: 500
        max_standard_order_id:
          type: integer
          example: 12345678
        num_custom_orders:
          type: integer
          example: 500
        max_custom_order_id:
          type: integer
          example: 12345678
      type: object